import os

project_root = os.path.abspath('../../')
build_subdir = 'build-scons'


cpp_path = ['include',
            'contrib/jsoncpp/include'
           ]
cpp_path = [os.path.join(project_root, x) for x in cpp_path]


cpp_flags = ['-g',
             '-Wall',
             '-std=c++11',
             '-stdlib=libc++',
             '-pthread'
            ]
compiler = 'clang++'


env = Environment(
    CXX = compiler,
    CPPFLAGS = cpp_flags,
    CPPPATH = cpp_path
)

SConscript('SConscript',
           variant_dir = build_subdir,
           exports = ['env']
          )
