Import('env')

json_cpp_cpp_path = '../../../contrib/jsoncpp/src/lib_json/'
json_cpp_cpp_files = []
for filename in ['json_value.cpp', 'json_reader.cpp', 'json_writer.cpp']:
    json_cpp_cpp_files.append(json_cpp_cpp_path + filename)

cpp_files = ['parse_protocol.cpp'] + json_cpp_cpp_files

protocol_lib = env.StaticLibrary(target = 'protocol',
                                 source = cpp_files
                                )
