# vim: filetype=python

Import('env')

cpp_files = ['string_conversion.cpp',
             'factory.cpp',
             'move_to_closest_strategy.cpp',
             'predictive_strategy.cpp',
             'do_nothing_strategy.cpp',
             'drunk_strategy.cpp',
             'buffalo_strategy.cpp',
             'random_acceleration_strategy.cpp'
            ]

strategies_lib = env.StaticLibrary(target = 'strategies',
                                   source = cpp_files
                                  )

Return('strategies_lib')
