Import('env')

cpp_files = ['move_to_closest_strategy.cpp',
             'predictive_strategy.cpp',
             'do_nothing_strategy.cpp'
            ]
strategies_lib = env.StaticLibrary('strategies', cpp_files)
