######################################################################
# Automatically generated by qmake (2.01a) Fri May 9 16:12:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT       += core gui

# Input
SOURCES += main.cpp ipc.h client.cpp
HEADERS += ipc.h fieldview.h

QMAKE_CXXFLAGS += -Wall -pedantic -std=c++11
