# vim: filetype=python

Import('env')

cpp_files = ['geometry.cpp',
             'thread_pool.cpp'
            ]

util_lib = env.StaticLibrary(target = 'util',
                             source = cpp_files
                            )

Return('util_lib')
