Import('env')

cpp_files = ['gamer.cpp']
env.Program(target = 'gamer', 
            source = cpp_files, 
            LIBS = ['libprotocol.a',
                    'libstrategies.a',
                    'libutil.a',
                    'c++',
                    'pthread'
                   ], 
            LIBPATH = ['../../../lib/protocol/build-scons',
                       '../../../lib/util/build-scons',
                       '../../../src/strategies/build-scons'
                      ]
           )
